name: Publish Docker image

on:
  workflow_dispatch: {}             
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      
      - name: Publish to Docker Hub
        uses: bitovi/github-actions-docker-publish@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME2 }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
      

